NumPy введение.                       mms,25.09.22

https://physics.susu.ru/vorontsov/language/numpy.html    -очень полная информация по библиотеке

In [ ]:
nums = [1, 3, -1]
for num in nums:
    num += 1
    print(num)
nums

In [ ]:
#Создание массива(вектора) из списка
import numpy as np
#from numpy import *
v = np.array(nums,dtype=float)
print(v)
v

In [ ]:
v1=np.arange(1, 5)              #Cоздает вектор с элементами от 1 до 4
#Cравните вывод:
print(v1)
print(*v1)        
v1

In [ ]:
# Создаем двухмерный массив
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10], [9,10,11]])
print(M[0, 1])        
M[0,1]=100          #Изменение элемента массива
M

In [ ]:
print(M.size, M.shape, len(M), M.ndim)

In [ ]:
#Все элементы в массиве numpy принадлежат одному типу
x = np.array([1.0, 2.0])   # Автоматический выбор типа
print(x.dtype)         

x = np.array([1.0, 2.0], dtype=np.int32)   # Принудительное задание типа
print(x.dtype)             

In [ ]:
b = np.eye(4)
print ("Единичная матрица:\n", b)

c = np.ones((2, 5))
print ("Матрица из всех единиц:\n", c)

z = np.zeros((3, 3))
print ("Матрица из всех нулей:\n", c)


In [153]:
v2 = np.arange(0, 24, 2) 
print ("Вектор-столбец:\n", v2)

d = v2.reshape((3, 4))
print ("Матрица:\n", d)


Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]
Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [ ]:
d = np.full((2,2), 7)  # Создает матрицу (1, 2) заполненую заданным значением
print(d)               
                      
e = np.random.random((2,2))   # cоздает матрицу заполненую случаными числами из интервала (0, 1)
print(e)      

f=np.random.randint(1,4,10).reshape(2,5)    # cоздает матрицу 2x5 заполненую случаными числами из интервала [1, 4)
print(f) 

In [ ]:
#Cрезы.
print(M)
#M[:, 1]
#M[0:2, 1]
#M[0:-1, 1]
#M[1]
#M[:, [0,2]]

#print(v)
#M[0, :] = v
#M

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
print(M)
print(v)

M+M                   #поэлеметное сложение
#M*M                  #поэлеметное(!) умножение
#M*v                  
#np.sin(M)            # поэлементное применение функции sin

#np.dot(M, M)         #матричное умножение

#np.linalg.det(M)     #определитель
#np.trace(A)          #cумма диагональных элеменов    

#Решение системы линейных уравнений Mx=y. (Построим у для x=v и проверим, что найденное решение совпадет с v)
#y = np.dot(M, v)
#print(y)
#x=np.linalg.solve(M, y)
#x


In [ ]:
#O копировании
print(M)
C = M[1:3, 1:3]
print(C)
C[1:] =100
print(C)
print(M)
#C = M[1:3, 1:3].copy()    - а правильно было так!

In [ ]:
#Транспонирование
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [ ]:
#Ранг матрицы (мах число незаисимых строк столбцов)
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)
print(r)

In [ ]:
#Обратите внимание: вектор (одномерный массив) и вектор-столбец или вектор-строка (двумерные массивы) 
#являются различными объектами в NumPy, хотя математически задают один и тот же объект. 
#В случае одномерного массива shape состоит из одного числа и имеет вид (n,), где n — длина вектора. 
#В случае двумерных векторов в shape присутствует еще одна размерность (n,1).
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print (f'a:\n {a}\n {a.shape}')
print (f'b:\n {b}\n {b.shape}\n')

#В большинстве случаев неважно, какое представление использовать, потому что часто 
#срабатывает приведение типов. Но некоторые операции не работают для одномерных массивов. 
#Например, транспонирование:
print(a.T)
print(b,b.T)


In [98]:
#Норма 
#linalg.norm(a[, ord])   
a = np.array([2, 2, -3])
print('L1 норма вектора a:', np.linalg.norm(a, ord=1))
print('L2 норма вектора a:', np.linalg.norm(a, ord=2))

L1 норма вектора a: 7.0
L2 норма вектора a: 4.123105625617661


In [ ]:
#Обратная матрица(для квадратных невырожденных матриц)
A = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
D = np.array([[1, 2, 1], [1, 1, 4], [1, 8, 4], [2, 3, 6]], dtype=np.float32)
D
print(np.linalg.inv(A))
print(np.linalg.pinv(D))     #Псевдо-обратная матрица (Мура-Пенроуза) для произвольных матриц

In [ ]:
np.linalg.eig(A) 	    #собственные значения и собственные вектора квадратной матрицы

In [ ]:
#Cоздание сеток
#Равномерный набор заданного числа точек(11) на заданном интрвале [-5,5]
x = np.linspace(-5, 5, 11)   
print(x)

#Набор последовательных чисел из промежутка [start, stop) с заданным шагом step
#arange([start,] stop [, step,][, dtype])
x=np.arange(4.0)
print(x)

#Логарифмический набор точек
x=np.logspace(2.0, 3.0, num=4, base=2.0)
print(x)

#Два вектора, описывающих точки ортогональной сетки.
X, Y = np.meshgrid([1,2,3], [4,5,7])

In [ ]:
import numpy as np
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
print(np.add(M,M))
#from scipy import linalg, sparse
linalg.expm(M)

array([[2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3]])

In [ ]:
#Задания

#Заданиe_1
#Создайте вектор из нулей длины 12, но его 4-й елемент должен быть равен 1

#Заданиe_2
#Создайте матрицу (3, 3), заполненую от 0 до 8

#Задание_3
#Напишите функцию, которая принимает размер матрицы, а возвращает матрицу, 
#сформированною ее по формуле
#A[n,m] = n + 10 * m

#Заданиe_4
#Создайте рандомный вектор и отсортируйте его по убыванию.(Найдите и разберитесь 
#с функцией сортировки)

#Заданиe_5
#Напишите свои функции вычисления L1 и L2 нормы вектора и сравните с np.linalg.norm. 
#Для каждой нормы напечатайте в строку оба значения и результат сравнения.
#Оформите все в виде функции с одним аргументом(входным вектором). 

#Задание_6
#Напишите функцию, принимающую на вход два вектора, которая вычисляет 
#угол между этими векторами.

#Задание_7
#Сгенерируйте матрицу 4x4 из целых случайных чисел.
#Если определитель матрицы не равен 0, то вычислите обратную матрицу.
#Проверьте, что произведение A на обратную должна быть единичной.

#Заданиe_8
#Написать функцию select_even(arr), принимающую на вход массив целых чисел arr 
#и возвращающую новый массив, который состоит из всех чётных элементов arr.

#Заданиe_9
#Написать функцию wipe_even(arr, target_value, in_place), принимающую на вход массив целых 
#чисел arr, и возвращающую массив, полученный из arr путём замены всех чётных элементов на 
#target_value. Если target_value не указано, то оно должно считаться равным числу 0. 
#Если указан параметр in_place и он равен True, то функция должна менять исходный массив, 
#а если не указан или указан в False, то сохранять его неизменным. 

#Заданиe_10
#Постройте 3D-график функции z=x^2-y^2 на области x: [-1.5, 1.5], y: [-1,1] 