In [2]:
#задание 1
#Несовсем понимаю, что значит вектор из 0, с 4ым элементом равным 1. 
#и где он находиться в R^4 or R^n, можно конечно ввести метрику в 12, но как-то мне кажется не это иммелось ввиду

In [23]:
#задание 2
import numpy as np
v2 = np.arange(9)
print(v2)
m = v2.reshape((3,3))
print(m)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#задание 3
import numpy as np
def matr(n, m):
    z = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            z[i][j]= i + 10 * j
    return z


print(matr(5,5))

[[ 0. 10. 20. 30. 40.]
 [ 1. 11. 21. 31. 41.]
 [ 2. 12. 22. 32. 42.]
 [ 3. 13. 23. 33. 43.]
 [ 4. 14. 24. 34. 44.]]


In [30]:
#задание 4
v = np.random.randint(1, 100, 10)
print(sorted(v)[::-1])

[92, 89, 79, 66, 64, 37, 33, 11, 8, 6]


In [31]:
#Заданиe_5
def l1(a):
    s = 0
    for x in a:
        s += abs(x)
    return s 


def l2(a):
    s = 0 
    for x in a:
        s += x**2
    return s**0.5


v = np.random.randint(1, 10, 3)
print(np.linalg.norm(v, ord=1), l1(v), l1(v)==np.linalg.norm(v, ord=1))
print(np.linalg.norm(v, ord=2), l2(v), l2(v)==np.linalg.norm(v, ord=2))



24.0 24 True
13.856406460551018 13.856406460551018 True


In [40]:
#Задание_6
def lenght(a):
    s = 0
    for x in a:
        s += x**2 
    return s**0.5

def multiplication(a, b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b [i]
    return s 
 
def angel(a, b):
    return np.arccos(multiplication(a,b)/(lenght(a)*lenght(b)))


print(angel([1,0],[0,1]), 'Пи радиан')



1.5707963267948966 Пи радиан


In [43]:
#Задание_7

m =  np.random.randint(1,100,16).reshape(4, 4)
print(m)
print(np.linalg.det(m))

[[82 90 35 28]
 [42 76 46 74]
 [ 8 65 59 48]
 [92  7  6 51]]
10438990.0
